config/routes.rb
Shooteditpublish::Application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout' }
  match '/help',      to: 'static_pages#help',      via: 'get'
  match '/about',     to: 'static_pages#about',     via: 'get'
  match '/jesus',     to: 'static_pages#jesus',     via: 'get'
  match '/acknowledgements', to: 'static_pages#acknowledgements', via: 'get'

  root 'static_pages#home'
  resources :points, path: "/points"
  resources :users, only: [:index, :create]
  resources :users, path: "", only: :show

end

app/models/point.rb
class Point < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  default_scope -> { order('created_at DESC') }
  validates :activity, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :points, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  validates_uniqueness_of :username
  validates_presence_of :username
  validates :username, length: { in: 1..20 }, exclusion: {in: %w[sign_in users user sign_out help jesus new]}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX }


  def to_param
    username
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      registration_params = [:email, :username, :password, :password_confirmation]

      if params[:action] == 'create'
        devise_parameter_sanitizer.for(:sign_up) { 
          |u| u.permit(registration_params) 
        }
      end
    end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  before_filter :authenticate_user!, only: :destroy
  before_action :correct_user,       only: :destroy

  def create
    @point = current_user.points.build(point_params)
    if @point.save
      flash[:success] = "Points awarded!"
      redirect_to user_path(current_user)
    else
      render root_path
    end
  end

  def destroy
    @point.destroy
    redirect_to user_path(current_user)
  end

  private
    def point_params
      params.require(:point).permit(:value, :activity)
    end

    def correct_user
      @point = current_user.points.find_by(id: params[:id])
      redirect_to root_url if @point.nil?
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_filter :authenticate_user!, only: :jesus

  def home
    @point = current_user.points.build if signed_in?
  end

  def help
  end

  def about
  end

  def acknowledgements
  end

  def jesus
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, only: :index
 
  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find_by_username(params[:id])
    @points = @user.points.paginate(page: params[:page], :per_page => 5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = "Shoot Edit Publish"

    if page_title.empty?
      base_title
    else 
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="col-xs-3">
    <small>
      &copy; <a href="//simplyluke.com/" target="_blank">Luke Wright</a> 2013
     </small>
   </div>
   <div class="col-xs-3">
     <div class="social-icons">
       <a href="//github.com/simplyluke/shoot-edit-publish" target="_blank"><span class="icon ion-social-github"></span></a>
       <a href="//twitter.com/shoot_edit/" target="_blank"><span class="icon ion-social-twitter"></span></a>
    </div>
  </div>


  <nav class="col-xs-6 pull-right">
    <ul>
      <li><%= link_to about_path do %>
        <span class="icon ion-ios7-information-outline"></span> About
      <% end %>
      </li>
      <li> <%= link_to help_path do %>
        <span class="icon ion-help-buoy"></span> Help
      <% end %>
      <li><%= link_to acknowledgements_path do %>
        <span class="icon ion-star"></span> Acknowledgements
      <% end %>
      </li>
      <% if user_signed_in? %>
        <li><%= link_to edit_user_registration_path do %>
          <span class="icon ion-gear-b"></span> Edit Account
        <% end %>
        </li>
      <% end %>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse-1">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand', id: 'logo' do %>
        <span class="icon ion-camera"></span>
      <% end %>
    </div>
    <div class="collapse navbar-collapse navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right nav-controls">
        <li class="<%= 'active' if current_page?(root_path) %>">
        <%= link_to 'Home', root_path %>
        </li> 

        <% if user_signed_in? %>

        <li class="<%= 'active' if current_page?(users_path) %>">
        <%= link_to 'Users', users_path %>
        </li>

        <li class="<%= 'active' if current_page?(user_path(current_user)) %>">
        <%= link_to 'Me', user_path(current_user) %>
        </li>

        <li class="<%= 'active' if current_page?(destroy_user_session_path) %>">
        <%= link_to 'Sign out', destroy_user_session_path, method: "delete" %>
        </li>

        <% else %>
        <li class="<%= 'active' if current_page?(new_user_session_path)%>">
        <%= link_to 'Sign in', new_user_session_path %>
        </li>
        <li class="<%= 'active' if current_page?(new_user_registration_path)%>">
        <%= link_to 'Sign up', new_user_registration_path %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'favicon.ico' %>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %> 
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %> alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><%= value %></div>
    <% end %>
    <%= yield %>
  </div>

  <div class="container">
  <%= render 'layouts/footer' %>
</div>
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-46835005-1', 'shootedit.net');
ga('send', 'pageview');

</script>
</body>
</html>

app/views/points/_point.html.erb
<li class="point-listing">
  <div>
    <div class="point-activity">
    <% if point.activity == "shot" %>
    <span class="icon ion-camera"></span> Shot 
    <% elsif point.activity == "edited" %>
    <span class="icon ion-monitor"></span> Edited
    <% elsif point.activity == "published" %>
    <span class="icon ion-upload"></span> Published
    <% else %>
    point.activity
    <% end %>
    
    | <%= point.value %> points 
    </div>
  </div>
  <span class="posted-ago">Posted <%= time_ago_in_words(point.created_at) %> ago.</span>
  <% if current_user == point.user %>
  <%= link_to point, method: :delete, class: 'delete-point', data: { confirm: "Sure you want to delete?" } do %>
   <span class="icon ion-trash-b"></span> Delete
  <% end %> 
  <% end %>
</li>

app/views/static_pages/_new.html.erb
<div class="row home-buttons">
  <div class="well col-sm-3">
    <h3>Shot - 50 Points</h3>
    <span class="home-icon icon ion-camera"></span>
    <%= form_for @point do |f| %>
      <%= f.hidden_field :activity, :value => "shot" %>
      <%= f.hidden_field :value,  :value => 50 %>
    <%= f.submit "Shot", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>

  <div class="well col-sm-3 col-sm-offset-1">
    <h3>Edited - 50 Points</h3>
    <span class="home-icon icon ion-monitor"></span>
    <%= form_for @point do |f| %>
      <%= f.hidden_field :activity, :value => "edited" %>
      <%= f.hidden_field :value,  :value => 50 %>
    <%= f.submit "Edited", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>

  <div class="well col-sm-3 col-sm-offset-1">
    <h3>Published - 100 Points</h3>
    <span class="home-icon icon ion-upload"></span>
    <%= form_for @point do |f| %>
      <%= f.hidden_field :activity, :value => "published" %>
      <%= f.hidden_field :value,  :value => 100 %>
    <%= f.submit "Published", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About Shoot Edit Publish</h1>
<hr>
<p>Shoot Edit Publish is a project by <a href="http://simplyluke.com/" target="_blank">Luke Wright</a>.</p> 

<p>I believe that the key to becoming a better photographer is through practice, and providing a way to publicly boast about practicing and being rewarded for it is an excellent way to encourage practice.</p>

<p>Shoot Edit Publish was built using Ruby on Rails to further my knowledge of the framework. Check out the code on <a href="//github.com/simplyluke/shoot-edit-publish" target="_blank">Github</a></p>

app/views/static_pages/acknowledgements.html.erb
<% provide(:title, 'Acknowledgements') %>
<h1>Acknowledgements</h1>
<hr>
<ul>
  <li><a href="http://zachlatta.com/" target="_blank">Zach Latta</a> - Code review, patiently showing me rails &amp; vim magic.</li>
  <li><a href="http://ionicons.com/" target="_blank">Ionicons</a> - Icons</li>
</ul>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<hr>
<p>If you run into any issues email me at <a href="mailto:luke@simplyluke.com">luke@simplyluke.com</a>

app/views/static_pages/home.html.erb
<% if user_signed_in? %>
  <h1>Shoot Edit Publish</h1>
  <hr>
  <h2>Today I...</h2>
  <%= render 'new' %>
<% else %>

<div class="jumbotron">
  <h1>Shoot Edit Publish</h1>
  <p>Shoot Edit Publish makes your photography workflow fun and rewarding! <br> Gain points while becoming a better photographer.</p>
  <%= link_to "Sign up today!", new_user_registration_path, class: 'btn btn-primary btn-lg', role: 'button' %>
</div>

<% end  %>

app/views/static_pages/jesus.html.erb
<% provide(:title, 'Jesus') %>

<div class="jesus">
<img src="https://31.media.tumblr.com/c4f70d048712d5deb75db1d98b93bc7e/tumblr_mvrlm1MVKR1rtrhmwo1_500.gif" alt="JESUS" />
</div>

app/views/users/_user.html.erb
<li>
  <%= link_to user.username, user_path(user) %>
</li>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>
<h1>Users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>
<h1><%= @user.username %></h1>


<% if @user.points.any? %>
<div class="col-md-4 col-sm-5">
  <h3>Total Points: <strong><%= @user.points.sum('value') %></strong></h3>
  <a href="https://twitter.com/share" class="twitter-share-button" data-lang="en" data-count="none" data-via="shoot_edit" data-text="Check out my progress on Shoot Edit Publish, I have <%= @user.points.sum('value') %> points so far! shootedit.net<%= url_for @user %>">Tweet</a>
  <ul class="point-list ">
    <%= render @points %>
  </ul>
  <%= will_paginate(@points, :renderer => WillPaginate::ActionView::LinkRenderer) %>
</div>

<% else %>

<h3>No points!</h3>

<% end %>

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>